services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 1000
        gid: 1001
        user: "jupyter"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8gb'
    volumes:
      - ./:/kaggle
    working_dir: /kaggle
    ports:
      - "8889:8889"
    tty: true
